name: CI

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref =='refs/heads/develop'
        run: npx surge --project ./build --domain reactapp-lima.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.LOGIN_SURGE}}
          SURGE_TOKEN: ${{secrets.TOKEN_SURGE}}